#QUESTION1 :)
SELECT I.ASIGNATURA_CODIGO
FROM IMPARTIR I
WHERE I.PROFESORES_ID IN (SELECT P.ID
						  FROM PROFESORES P
						  WHERE UPPER(P.NOMBRE) = 'Manuel' AND UPPER(P.APELLIDO1) = 'Enciso');
						
                        
					
#QUESTION2 :)
SELECT DISTINCT M.ALUMNOS_DNI FROM MATRICULAR M WHERE (M.ASIGNATURAS_CODIGO,M.GRUPO,M.CURSO ) IN 
																	(SELECT I.ASIGNATURA_CODIGO,I.GRUPO,I.CURSO
																	FROM IMPARTIR I
																	WHERE UPPER(I.PROFESORES_ID) = 'C-34-TU-00');

#QUESTION3 :)
SELECT D.NOMBRE DEPARTAMENTO, SUM(ASI.CREDITOS) NUMERO_CREDITOS
FROM ASIGNATURAS ASI LEFT OUTER JOIN DEPARTAMENTOS D ON ASI.DEPARTAMENTO_CODIGO=D.CODIGO
GROUP BY D.NOMBRE;

#QUESTION4 :)
SELECT P.DESPACHO,SUM(I.CARGA_CREDITOS) TOTAL_CREDITOS
FROM PROFESORES P JOIN IMPARTIR I ON I.PROFESORES_ID = P.ID AND P.DESPACHO IS NOT NULL
GROUP BY P.DESPACHO;

#QUESTION5 :)
SELECT DISTINCT CONCAT(AL.NOMBRE,' ',AL.APELLIDO1) ALUMNO , ASI.NOMBRE ASIGNATURA
FROM (ALUMNOS AL JOIN MATRICULAR M ON M.ALUMNOS_DNI=AL.DNI) JOIN ASIGNATURAS ASI ON M.ASIGNATURAS_CODIGO=ASI.CODIGO
WHERE ASI.CREDITOS = ( SELECT MAX(ASI2.CREDITOS)
FROM (ALUMNOS AL2 JOIN MATRICULAR M2 ON M2.ALUMNOS_DNI=AL2.DNI) JOIN ASIGNATURAS ASI2 ON M2.ASIGNATURAS_CODIGO=ASI2.CODIGO
WHERE AL2.DNI=AL.DNI);

#QUESTION6 :)

SELECT D.NOMBRE DEPARTAMENTO,ASI2.NOMBRE ASIGNATURA
FROM ASIGNATURAS ASI2 JOIN DEPARTAMENTOS D ON ASI2.DEPARTAMENTO_CODIGO=D.CODIGO
WHERE (ASI2.DEPARTAMENTO_CODIGO, ASI2.CREDITOS) IN ( SELECT ASI.DEPARTAMENTO_CODIGO, MIN(ASI.CREDITOS)
													 FROM ASIGNATURAS ASI 
													 GROUP BY ASI.DEPARTAMENTO_CODIGO);

#QUESTION7 :)
SELECT D.NOMBRE DEPARTAMENTO
FROM DEPARTAMENTOS D,
(SELECT COUNT(*) AS NUMERO_ASIGNATURAS FROM ASIGNATURAS ASI GROUP BY ASI.DEPARTAMENTO_CODIGO) AS E
ORDER BY E.NUMERO_ASIGNATURAS DESC LIMIT 1;

#QUESTION8 :)
SELECT P.NOMBRE,P.APELLIDO1,P.APELLIDO2
FROM PROFESORES P JOIN IMPARTIR I ON I.PROFESORES_ID=P.ID
GROUP BY P.NOMBRE,P.APELLIDO1,P.APELLIDO2
HAVING SUM(I.CARGA_CREDITOS) > (
SELECT AVG(TEMP.SUMA) FROM (SELECT SUM(CARGA_CREDITOS)'SUMA' FROM IMPARTIR GROUP BY PROFESORES_ID) AS TEMP);

#QUESTION9 :)
SELECT DISTINCT D.NOMBRE
FROM ASIGNATURAS ASI2 JOIN DEPARTAMENTOS D ON ASI2.DEPARTAMENTO_CODIGO=D.CODIGO
WHERE D.CODIGO  NOT IN(SELECT ASI.DEPARTAMENTO_CODIGO
				   FROM ASIGNATURAS ASI WHERE ASI.CREDITOS > 6);
                   
				
#QUESTION10 :)     
SELECT CONCAT(P1.NOMBRE,' ',P1.APELLIDO1,' ',IFNULL(P1.APELLIDO2,' ')) NOMBRE1 ,CONCAT(P2.NOMBRE,' ',P2.APELLIDO1,' ',IFNULL(P2.APELLIDO2,' ')) NOMBRE2
FROM PROFESORES P1,PROFESORES P2
WHERE P1.ID < P2.ID AND (P1.ID,P2.ID)  NOT IN ( 
SELECT I1.PROFESORES_ID, I2.PROFESORES_ID
FROM MATRICULAR M1 JOIN IMPARTIR I1 ON (M1.CURSO=I1.CURSO AND M1.GRUPO=I1.GRUPO AND M1.ASIGNATURAS_CODIGO = I1.ASIGNATURA_CODIGO)
JOIN
MATRICULAR M2 JOIN IMPARTIR I2 ON (M2.CURSO=I2.CURSO AND M2.GRUPO=I2.GRUPO AND M2.ASIGNATURAS_CODIGO = I2.ASIGNATURA_CODIGO)
ON M1.ALUMNOS_DNI=M2.ALUMNOS_DNI ) ;

















